// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgcGZvoqRsg_3R-qRQqE5A1EdmRTQLoCg',
    appId: '1:262068956843:web:26c34537e82f70088411ee',
    messagingSenderId: '262068956843',
    projectId: 'mascotas-c4cab',
    authDomain: 'mascotas-c4cab.firebaseapp.com',
    storageBucket: 'mascotas-c4cab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDydG7CfChn7mXBWmZOIn_1DCqDa_O7dE',
    appId: '1:262068956843:android:4f8d7725b5155da68411ee',
    messagingSenderId: '262068956843',
    projectId: 'mascotas-c4cab',
    storageBucket: 'mascotas-c4cab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVKwwGfAwu0vJU49wmcVB1-F9roUkQOOk',
    appId: '1:262068956843:ios:682d61ab93f0d7738411ee',
    messagingSenderId: '262068956843',
    projectId: 'mascotas-c4cab',
    storageBucket: 'mascotas-c4cab.firebasestorage.app',
    iosBundleId: 'com.example.fireCrud5a25',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgcGZvoqRsg_3R-qRQqE5A1EdmRTQLoCg',
    appId: '1:262068956843:web:90ff3ef433a98db68411ee',
    messagingSenderId: '262068956843',
    projectId: 'mascotas-c4cab',
    authDomain: 'mascotas-c4cab.firebaseapp.com',
    storageBucket: 'mascotas-c4cab.firebasestorage.app',
  );
}
